/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adressbook;

/**
 *
 * @author ANIK
 */
public class homepage extends javax.swing.JFrame {

    /**
     * Creates new form homepage
     */
    public homepage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        logoPanel = new javax.swing.JPanel();
        textFieldOfLogo = new javax.swing.JTextField();
        buttonOfNext = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        logoPanel.setBackground(new java.awt.Color(153, 153, 153));
        logoPanel.setLayout(null);

        textFieldOfLogo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        textFieldOfLogo.setText("KANTI'S  ADDRESSBOOK  ");
        textFieldOfLogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldOfLogoActionPerformed(evt);
            }
        });
        logoPanel.add(textFieldOfLogo);
        textFieldOfLogo.setBounds(320, 170, 479, 49);

        buttonOfNext.setBackground(new java.awt.Color(255, 255, 255));
        buttonOfNext.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        buttonOfNext.setText("NEXT");
        buttonOfNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOfNextActionPerformed(evt);
            }
        });
        logoPanel.add(buttonOfNext);
        buttonOfNext.setBounds(1001, 504, 89, 51);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adressbook/5.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        logoPanel.add(jLabel1);
        jLabel1.setBounds(0, 0, 1100, 570);

        jLabel2.setText("jLabel2");
        logoPanel.add(jLabel2);
        jLabel2.setBounds(50, 126, 210, 220);

        getContentPane().add(logoPanel);
        logoPanel.setBounds(20, 70, 1102, 568);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldOfLogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldOfLogoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldOfLogoActionPerformed

    private void buttonOfNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOfNextActionPerformed
        homePage myHomePage= new homePage();
        myHomePage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonOfNextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonOfNext;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel logoPanel;
    private javax.swing.JTextField textFieldOfLogo;
    // End of variables declaration//GEN-END:variables
}
